### ISSUE TITLE
SparkR on JupyterHub missing

### ISSUE THREAD

**Issue by samelamin** [awsdocs/amazon-emr-release-guide#11]
The documentation states that SparkR is installed by default, but creating a brand new EMR(v 5.20.0) only lists 4 kernels

Pyspark, Pyspark3 , Python 3, and Spark

Can you explain to me how to enable SparkR on Jupyterhub notebooks?

**Comment by Hyurt** [comment]
Can't you use a bootstrap action ? 
Maybe you could base your bootstrap action on this https://gist.github.com/cosmincatalin/19ee904450284c97976a448695ee400c

**Comment by ghost** [comment]
@samelamin I'm in process of ripping this out of doc's now. Thanks for finding and reporting. I saw the answer on the forum here: https://forums.aws.amazon.com/thread.jspa?threadID=296459 Did you get those commands to work?
