### ISSUE TITLE
Add Scala version?

### ISSUE THREAD

**Issue by aurelien-clu** [awsdocs/amazon-emr-release-guide#15]
# Context

Using `scala 2.12` code compiled to a fat `jar` does not work with `EMR flink` because of a version mismatch. `Flink` uses `2.11` .

# The ask :smile: 

Could it be possible to have the `scala version` in the documentation for the following applications?

- `flink`
- `spark`
- it may apply to other applications I am less familiar with

**Comment by ellkend-aws** [comment]
@aurelien-clu Thank you for opening this issue and for your patience. We've been working to better maintain the GitHub version of the EMR Release Guide. I'll add your request to the team's list of items for consideration, as we get frequent requests to provide more detailed language version information.
