### ISSUE TITLE
Multiple m4.large entries on Task Configuration documentation

### ISSUE THREAD

**Issue by kimbria7** [awsdocs/amazon-emr-release-guide#2]
Not sure why, but there are 2 entries for m4.large instance default configurations at  amazon-emr-release-guide/doc_source/emr-hadoop-task-config.md

The correct one seems to be the second one closer to the end of the page

**Comment by ghost** [comment]
Hey there, sorry for taking so long to get this fix. Had a bit of a confusing build issue on my end that caused me to keep reverting the fix. Nevertheless, I should have responded earlier that I was on it. Fixed now. Thanks for using EMR and for making the doc's better!
