### ISSUE TITLE
release note sync discrepancy: AWS Athena now supports Apache Hudi so the limitation noted should be deleted

### ISSUE THREAD

**Issue by fred-oko** [awsdocs/amazon-emr-release-guide#20]
In https://github.com/awsdocs/amazon-emr-release-guide/blob/master/doc_source/emr-hudi-considerations.md#considerations-and-limitations-for-using-hudi-on-amazon-emr  the statement "Athena not supported – Querying Hudi datasets using Amazon Athena is not supported." is no longer valid per https://aws.amazon.com/about-aws/whats-new/2020/07/amazon-athena-adds-support-querying-apache-hudi-datasets-amazon-s3-based-data-lake/

**Comment by ellkend-aws** [comment]
Closing this issue, as it's been addressed by [this PR](https://github.com/awsdocs/amazon-emr-release-guide/pull/24).
