### ISSUE TITLE
Include python minor version

### ISSUE THREAD

**Issue by tekumara** [awsdocs/amazon-emr-release-guide#21]
The release docs say Python 3 is installed but which minor version? 3.6, 3.7, or 3.8?

**Comment by ellkend-aws** [comment]
@tekumara Thank you for opening this issue. We're working with the larger EMR team to provide more detailed version information for components such as Python.  I'll add your request to the team's list of items for consideration and then close this issue.

**Comment by tekumara** [comment]
Thanks @ellkend-aws if this issue is closed, what's the best way to track if/when the docs are updated?

**Comment by tekumara** [comment]
@ellkend-aws any updates on whether this can be added to the docs?

**Comment by ellkend-aws** [comment]
@tekumara Thank you for checking in. This issue is still on our list of documentation improvements for consideration.

 I'll reopen this issue so that we can provide updates here about progress.

**Comment by tekumara** [comment]
How did you go with this one?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
