### ISSUE TITLE
Wrong version of Flink in picture of 5.14.0

### ISSUE THREAD

**Issue by tbuenger-zz** [awsdocs/amazon-emr-release-guide#3]
The picture shows still Flink in Version 1.4.0 although remaining text, tables and aws console tell it's 1.4.2.

**Comment by ghost** [comment]
Hi Thomas! Good catch! I'll get this fixed and publish the update soon. Thank you!

**Comment by ghost** [comment]
Hi @tbuenger! You should see the fix in now. Sorry for the delay responding. Thanks again for pointing out the error.
