### ISSUE TITLE
Include process for existing EMR

### ISSUE THREAD

**Issue by kination** [awsdocs/amazon-emr-release-guide#31]
Hello,

In following doc
https://github.com/awsdocs/amazon-emr-release-guide/blob/main/doc_source/emr-spark-glue.md#specifying-aws-glue-data-catalog-as-the-metastore,

On topic `To specify the AWS Glue Data Catalog as the metastore for Spark SQL using the console`, there are guide for when creating cluster, but I couldn't find how to change current config in existing EMR cluster.

Could you help?

**Comment by ellkend-aws** [comment]
@djKooks Thank you for your request. I'll add this to the team's list of items for future consideration and then close this issue. In the meantime, I suggest that you post any questions you have about using Amazon EMR on AWS re:Post, which is a good resource: https://repost.aws/
