### ISSUE TITLE
Missing documentation on EMR 6.6.0

### ISSUE THREAD

**Issue by lwoerdeman** [awsdocs/amazon-emr-release-guide#32]
I see that EMR 6.6.0 is now available via AWS Console. There is no documentation corresponding with this release.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
