### ISSUE TITLE
Missing Amazon EMR releases in "Amazon EMR what's new history"

### ISSUE THREAD

**Issue by ZachTylerPruitt** [awsdocs/amazon-emr-release-guide#36]
The following Amazon EMR releases are missing from [Amazon EMR what's new history](https://github.com/awsdocs/amazon-emr-release-guide/blob/main/doc_source/emr-whatsnew-history.md)
|Amazon EMR release|
|----|
|6.3.1|
|6.3.0|
|6.2.1|
|6.1.1|
|6.0.1|
|5.36.0|
|5.33.1|
|5.33.0|
|5.32.1|
|5.31.1|
|5.30.2|
|5.27.1|
|5.23.1|
|5.21.2|
|5.20.1|
|5.19.1|
|5.18.1|
|5.17.2|
|5.16.1|
|5.15.1|
|5.14.2|
|5.13.1|
|5.12.3|
|5.11.4|
|5.10.1|
|5.9.1|
|5.8.3|
|5.7.1|
|5.6.1|
|5.5.4|
|5.4.1|
|5.3.2|
|5.2.3|
|5.1.1|
|4.9.6|
|4.8.5|
|4.7.4|
|4.1.0|
|4.0.0|

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
