### ISSUE TITLE
Dead Links for "Edit this page on GitHub"

### ISSUE THREAD

**Issue by ZachTylerPruitt** [awsdocs/amazon-emr-release-guide#37]
The following releases are showing up in the online documentation but are missing from this repository so they have dead links for "Edit this page on GitHub"
|Amazon EMR Release|GitHub Links|
|-|-|
|6.9.0|[Edit this page on GitHub](https://github.com/awsdocs/amazon-emr-release-guide/tree/main/doc_source/emr-690-release.md)|
|6.8.0|[Edit this page on GitHub](https://github.com/awsdocs/amazon-emr-release-guide/tree/main/doc_source/emr-680-release.md)|
|6.7.0|[Edit this page on GitHub](https://github.com/awsdocs/amazon-emr-release-guide/tree/main/doc_source/emr-670-release.md)|
|6.6.0|[Edit this page on GitHub](https://github.com/awsdocs/amazon-emr-release-guide/tree/main/doc_source/emr-660-release.md)|
|5.36.0|[Edit this page on GitHub](https://github.com/awsdocs/amazon-emr-release-guide/tree/main/doc_source/emr-5360-release.md)|
|5.35.0|[Edit this page on GitHub](https://github.com/awsdocs/amazon-emr-release-guide/tree/main/doc_source/emr-5350-release.md)|

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
