### ISSUE TITLE
Incorrect default in documentation for hbase.region.max.filesize

### ISSUE THREAD

**Issue by jwtrhs** [awsdocs/amazon-emr-release-guide#5]
The docs say the default is 256MB, but it appears to actually be 10GB. Not sure if this is an issue with the documentation or the default is incorrect.

Here's what I get in my HBase config:
```
<property>
  <name>hbase.hregion.max.filesize</name>
  <value>10737418240</value>
  <final>false</final>
  <source>hbase-default.xml</source>
</property>
```

**Comment by ghost** [comment]
Hi Jonathan, thanks for using EMR and thanks for reaching out with the correction. I'll verify with engineering and update the doc.

**Comment by ghost** [comment]
Hey there, again. It looks like we have the same value you found documented as a default in these two places. Can you give me a link to where you found this bad info? Thanks again!

https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-hbase-s3.html
https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-hbase-configure.html

**Comment by jwtrhs** [comment]
Hi Jeff, yes it was on the second page:
https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-hbase-configure.html

Under the configuration section toward the end for `hbase.hregion.max.filesize` it notes the default is 256MB, and the example shows bumping it up to 1GB. I think this was the standard advice for an older version of HBase, but in the most recent version I believe the default is 10GB.

**Comment by ghost** [comment]
Ah. Nice! Great catch, I missed that (I've become too much the skimmer). I'll get it fixed. Thanks again, and thanks for the follow up!
